/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {

    private static Logger log = LoggerFactory.getLogger(Main.class);

    public static void main(String[] args) {
        log.info("Program invoked with {}", (Object) args);
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
