/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {

    @Test void appHasAGreeting() {
        App classUnderTest = new App();

        var greeting = classUnderTest.getGreeting();
        System.out.println(String.format("Found greeting '%s'", greeting));

        assertNotNull(greeting, "app should have a greeting");
    }
}
